-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL DEFAULT nextval('account_account_id_seq'::regclass),
    balance integer NOT NULL,
    bank_id integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT account_id PRIMARY KEY (account_id)
    );

CREATE TABLE IF NOT EXISTS public.account_transactions
(
    account_id integer NOT NULL,
    transaction_id integer NOT NULL,
    CONSTRAINT account_transactions_pk PRIMARY KEY (account_id, transaction_id)
    );

CREATE TABLE IF NOT EXISTS public.bank
(
    bank_id integer NOT NULL DEFAULT nextval('bank_bank_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT bank_pkey PRIMARY KEY (bank_id)
    );

CREATE TABLE IF NOT EXISTS public.transactions
(
    transaction_id integer NOT NULL DEFAULT nextval('transactions_transaction_id_seq'::regclass),
    amount integer NOT NULL,
    timestemp timestamp without time zone NOT NULL,
    currency text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id)
    );

ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT account_bank_id_fkey FOREIGN KEY (bank_id)
    REFERENCES public.bank (bank_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.account_transactions
    ADD CONSTRAINT account_transactions_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES public.account (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.account_transactions
    ADD CONSTRAINT account_transactions_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;